### PR TITLE
Improve normalization/calculation of event times

### LINKED ISSUE #16: Improve normalization/calculation of event times/position
In order to calculate the current sun position we rely on the event times provided by Home Assistant. These times are always the next time a given event occurs, e.g. "next_noon" will provide the time of today's noon only before it occurs, then it will report tomorrow's noon. The code tries to work around that limitation by normalizing all event times as if they all occur on the same day but uses UTC for normalization which may lead to errors - the further the local time zone is from UTC, the larger the error.

This was originally addressed by https://github.com/AitorDB/home-assistant-sun-card/pull/152 but then I dug deeper and discovered there are more issues with high latitude locations that experience times of the year when the sun doesn't rise or set. For those locations, Home Assistant reports the next sunrise even if it occurs many days after today. The only events that occur daily are solar noon and solar midnight (unused by the project), as they describe the highest and the lowest elevation of the sun regardless of whether it's above or below the horizon.

I'll open a PR after #4 is merged.

### PR DESCRIPTION
**Pull request by avataar**
## Overview

- Resolve issue with using UTC to normalize event times
- Handle high latitude locations where sunrise/sunset may not occur at certain times
- Show the time for events that don't occur as "-" (previously the whole label would disappear)
- Add interactive dev mode with predefined locations/dates to test things in a visual manner + python script to generate new test data if needed
- More tests

### Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Documentation update
- [x] Refactoring (of dev code)
- [ ] Other (please describe):

## Checklist

Please ensure that you have completed the following tasks before submitting your pull request:

- [x] I have read the [contributing guidelines](../CONTRIBUTING.md) for this project.
- [x] I have tested my changes against the `dev` branch (or another appropriate branch) and verified that they are working as expected.
- [x] I have updated the documentation (if applicable) to reflect my changes.
- [x] My changes adhere to the repository's code style guidelines.
- [x] My changes do not introduce any breaking changes or unexpected behaviors.

## Related Issues / Pull Requests

- Resolves #16 

## Additional Details

The new interactive dev mode allows you to try different locations and dates and observe the sun moving as if running in Home Assistant configured to that location on a given date. The speed and step can be changed to observe finer details. It also allows you to switch the language and dark/light theme. Just run yarn dev and open http://localhost:5000 :)

### CODE REVIEW

**Comment by avataar** [comment]
Hi @ThomDietrich and @edwardtfn,

Let me know what you think. I believe this really improves things.

Please try the new dev mode too. I recommend checking out Karasjok (at 69.7N!) in June or December :)

**Comment by edwardtfn** [comment]
> I recommend checking out Karasjok (at 69.7N!) in June or December :)

I've been quite close, both midsummer and midnight sun... 😉 
IMG_6111

**Comment by avataar** [comment]
@edwardtfn, any thoughts on this PR? If not I'll just merge it.

**Review by edwardtfn — APPROVED** [review]
No objections from my side.

**Pull request merged**
