### PR TITLE
Create lovelace-sun-card.js

### PR DESCRIPTION
**Pull request by edwardtfn**
To align with hacs requirements and stop failing validations

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Is it required to commit the build, rather than uploading as a Release asset?

Thanks for the PR, I want to wait for the decision in #11

**Comment by edwardtfn** [comment]
For having the HACS custom repository badge we just need the directory structure on the right format, which basically means having the file /dist/lovelace-sun-card.js in the repo (among other things that I believe are all set).
In order to publish at HACS default directory (HACS store?) you need also to pass the HACS Actions validation with the latest  merge. You will be requested to share the link for that validation instance.

**Comment by selfish** [comment]
@EdwardTfn and @ThomDietrich, let's wait for #4 before merging this. We don't need to keep the JavaScript file in the repository; it's only necessary for the release. GitHub Actions can add it to the release automatically, so that's the best option. This eliminates the need for manual updates and commits. #34 implements this, and I'll make it operational shortly.

**Comment by edwardtfn** [comment]
I'm totally fine with waiting... 😉

**Comment by avataar** [comment]
Obsolete - resolved through other PRs.

**Pull request closed without merging**
