### PR TITLE
Update de.json

### LINKED ISSUE #95: German translation
I think there is a plain mistake in the translation and another point at least of discussion.
First the term "Zenitwinkel" is plain wrong. It got its minimum at solar noon and when the sun is at the horizon.
As we are using the elevation here it should be "Höhenwinkel" which translates to elevantion angle and thats what we are talking about here.

The second issue is with the translation of "noon". Right now the translation is "Zenit" but that would be with a zenith angle of 0° (elevation of 90°).
Not 100% sure about the correct term here. It could simply be "Mittag" (simply translates to noon and is a combination of the word mid(mit) day(tag) ) but as "Mittag" is used for lunch and is more like a "12 o'clock" thingy I'm not sure if "Mittag" would be a good fit.
Another yet typical German word which would be a good fit is "Sonnenhöchststand" which means "peak of the sun" but its long and it will most likely destroy the layout cos in that line there would be "Morgendämmerung Sonnenhöchststand Abenddämmerung" in one line for "dawn noon dusk". Yeah, we like long words ... I know ... 

So "Sonnenhöchststand" might be the better or to say "more correct" term. But as its slightly more technical and as the term "Mittag" is used astronomically for "peak of sun" too I'd say we should go with "Mittag" for the translation of noon.
Also there are terms like "wahrer Mittag" (true mid-day) or "astronomischer Mittag" (astronomically mid-day) and as we are talking about the sun here its like to be understood like the way it should...

### PR DESCRIPTION
**Pull request by Dunstkreis**
fixed translation

### Type of Change

- [X] Bugfix

## Related Issues / Pull Requests

- Fixes #95

### CODE REVIEW

**Review by Gorm-Minetest — COMMENTED** [review]
Hello!
I'm a German user. So from my perspective this commit is ok and should be merged.

greetz gorm

**Comment by ThomDietrich** [comment]
Hey guys,
I need to question the translation of "Mittag". I would commonly say "Die Sonne steht im Zenit", not sure what "Mittag" is supposed to be. Would you have a reference or link o another well known weather page?

**Comment by Dunstkreis** [comment]
> I would commonly say "Die Sonne steht im Zenit", not sure what "Mittag" is supposed to be.

Yes and no. "Die Sonne steht im Zenit" is wrong if you are referring to the highest sun in Germany. Its not Zenit. Zenit is if its right above your head. (senkrecht über dir!) That's only possible between the tropical circles (Wendekreise).
I have heard it before too, but only because some folks are using wrong terms we shouldn't use them as a valid translation.

Like stated in the issue, I am not sure and open to better suggestions. The "most correct" term would be "Sonnenhöchststand" (kinda suns highest altitude). But to me that's to long and technical. 

"Mittag" as the mid of the day for me is kinda the best compromise. I know its not ideal, it could be confused with "mid of the day" whats used for 12 o'clock. Or it could be confused with "Mittagessen" (lunch). But as it would be displayed right between Morgendämmerung (dawn) and Abenddämmerung (dusk) the context would be clear.

As you requested a link: https://www.sonnenverlauf.de/
They are using "Sonnenhöchststand" - imo the "most correct" term.

And like posted on wikipedia: https://de.wikipedia.org/wiki/Sonnenstand
Der Moment des der Sonne (annähernd ihre Kulmination) ist Mittag (genauer: wahrer Mittag).
(The moment of the sun (approximately its culmination) is noon (more precisely: true noon).)

So we could use "wahrer Mittag" (true noon) here. And I thought about it too, but in my opinion this is more complicated than simply using "Mittag".

In the end it must be readable and understandable. If not using "Sonnenhöchststand" every other alternative would have its downsides. So as you are looking at the sun widget and its showing times for Sonnenaufgang, for Sonnenuntergang, for Dämmerung, one would not have a problem to get what is meant by "Mittag". Kinda similar to one can get what is meant by "Zenit" although one might look at it and stumbles across it because its just wrong. And that's why Mittag might not be optimal but in the end better than Zenit.

**Review by markusmazurczak — APPROVED** [review]
I think that it is not the best translation in tems of semantic accuracy but it is better then the actual translation.

**Review by ThomDietrich — APPROVED** [review]

**Pull request merged**
