### PR TITLE
Add Romanian translation

### PR DESCRIPTION
**Pull request by ThomDietrich**
# Pull Request Template for Home Assistant / Lovelace Card Repository

## Overview

Original pull request by @rumbu13: https://github.com/AitorDB/home-assistant-sun-card/pull/137

### Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe):

## Checklist

Please ensure that you have completed the following tasks before submitting your pull request:

- [ ] I have read the [contributing guidelines](../CONTRIBUTING.md) for this project.
- [ ] I have tested my changes against the `dev` branch (or another appropriate branch) and verified that they are working as expected.
- [ ] I have updated the documentation (if applicable) to reflect my changes.
- [ ] My changes adhere to the repository's code style guidelines.
- [ ] My changes do not introduce any breaking changes or unexpected behaviors.

## Related Issues / Pull Requests

Please include any related issues or pull requests that this change is associated with, and use the appropriate keywords (`Closes`, `Fixes`, `Resolves`) to automatically close the related issues when this pull request is merged.

- Closes #issue_number
- Fixes #issue_number
- Resolves #issue_number

## Additional Details

Please provide any additional information that you feel is relevant to this pull request, such as screenshots, code snippets, or examples.

### CODE REVIEW

**Comment by edwardtfn** [comment]
Could you please add the new language to the [README.md](https://github.com/rejuvenate/lovelace-horizon-card/blob/main/README.md#languages)?

**Comment by edwardtfn** [comment]
Please use #38 instead as I've added the changes in the other files.

**Comment by ThomDietrich** [comment]
No worries @edwardtfn :)
Would you like to add your completing changes from #38 as an additional commit and merge? Thanks!

**Comment by ThomDietrich** [comment]
Merged in https://github.com/rejuvenate/lovelace-horizon-card/commit/c1e42e376fbf26059c1741c8a28f9a69cc5b5c10

**Pull request closed without merging**
