### PR TITLE
Flip sunrise/sunset & dusk/dawn when southern_flip is true

### LINKED ISSUE #124: Ability to Flip Sunrise and Sunset times for Southern Hemisphere
Firstly, many thanks for the card - it is awesome! A request - Is it possible to create a parameter which allows the position of the Sunrise and Sunset times to be flipped? 

The southern_flip setting works well and allows the graph to move from sunrise to sunset correctly but this moves left to right, which is west to east in the southern hemisphere. 

The perfect end state would be to keep the nothern hemisphere right-to-left graph movement, but allow the change of the Sunset time to be on the left (instead of right) and the Sunrise time to be on the right (instead of the left). This will then show the correct movement of the sun in the southern hemisphere.

Many thanks again!

### PR DESCRIPTION
**Pull request by jesserockz**
# Pull Request Template for Home Assistant / Lovelace Card Repository

## Overview

Using the `southern_flip` config flag, I swapped the sunset/sunrise, dusk/dawn and moonrise/moonset elements.

### Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe):

## Checklist

Please ensure that you have completed the following tasks before submitting your pull request:

- [ ] I have read the [contributing guidelines](../CONTRIBUTING.md) for this project.
- [x] I have tested my changes against the `dev` branch (or another appropriate branch) and verified that they are working as expected.
- [x] I have updated the documentation (if applicable) to reflect my changes.
- [x] My changes adhere to the repository's code style guidelines.
- [x] My changes do not introduce any breaking changes or unexpected behaviors.

## Related Issues / Pull Requests

Please include any related issues or pull requests that this change is associated with, and use the appropriate keywords (`Closes`, `Fixes`, `Resolves`) to automatically close the related issues when this pull request is merged.

- Resolves #124

## Additional Details

Please provide any additional information that you feel is relevant to this pull request, such as screenshots, code snippets, or examples.

### CODE REVIEW

**Comment by LuNGFuLaGMaSTa** [comment]
Hi, shouldn't Moonrise and Moonset be switched around as well to ensure consistency?

**Comment by jesserockz** [comment]
> Hi, shouldn't Moonrise and Moonset be switched around as well to ensure consistency?

Yes, Updated =)

**Comment by ThomDietrich** [comment]
Hey @jesserockz, this looks great. Would you like to add anything to the README file?

**Comment by HoracioDos** [comment]
Hello! This fix would be very helpful.
Thanks!

**Comment by ThomDietrich** [comment]
Hey @jesserockz if you added a quick note the the README, I'd gladly merge your PR

**Comment by jesserockz** [comment]
Sorry @ThomDietrich I didnt really know what to add to the readme and forgot to come back to it

**Review by ThomDietrich — APPROVED** [review]
But you did now! Looks good :)

**Pull request merged**
