### PR TITLE
Commit `package-lock.json` and `yarn.lock`

### PR DESCRIPTION
**Pull request by MrBartusek**
# Pull Request Template for Home Assistant / Lovelace Card Repository

## Overview

Hey! It seams like this repo doesn't have `package-lock.json` and `yarn.lock` committed for some reason? These files should be definitely checked into source control as per [npm docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json)

image

### Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Documentation update
- [ ] Refactoring
- [x] Other (please describe): Repo maintaince

## Checklist

Please ensure that you have completed the following tasks before submitting your pull request:

- [ ] I have read the [contributing guidelines](../CONTRIBUTING.md) for this project.
- [x] I have tested my changes against the `dev` branch (or another appropriate branch) and verified that they are working as expected.
- [x] I have updated the documentation (if applicable) to reflect my changes.
- [x] My changes adhere to the repository's code style guidelines.
- [x] My changes do not introduce any breaking changes or unexpected behaviors.

## Related Issues / Pull Requests

None

## Additional Details

I've not read the contributing guidelines since they are not there 🤔

image

### CODE REVIEW

**Comment by avataar** [comment]
The project uses only yarn for building and as such it doesn't need npm at all. The committed yarn.lock is valid and sufficient for building.

**Comment by MrBartusek** [comment]
> The project uses only yarn for building and as such it doesn't need npm at all. The committed yarn.lock is valid and sufficient for building.

I actually need to disagree with you, as of the current state both systems are working fine with each other and it doesn't matter if the developer uses yarn or npm for dependencies and adding `package-lock.json` will simplify the life of people who use npm. It doesn't change how the yarn will do anything and won't generate a new lock file for npm users

**Comment by avataar** [comment]
Alas, it's not as simple as that. Sometimes one needs to override things using yarn or npm specific options. Real life example - local version of a package in the current dev version I'm working on. With yarn I have to set "resolutions", with npm it would be "overrides", both with different syntaxes. Rather than maintaining two independent build systems I prefer having a single one. Anyone who wishes to develop and contribute can simply install yarn.

**Comment by ThomDietrich** [comment]
@avataar I suggest to add a short section on How to contribute to the README. Looking at other examples on Github most of they support yarn AND npm. What's up with that?

**Comment by avataar** [comment]
@ThomDietrich, there's @edwardtfn's PR #33 aiming to improve contribution info. I'll add a comment there to add a section on building.

As far as I understood it, npm support is needed only for those who are lazy enough to not install yarn. Even if we have npm, any PR will still be built with yarn by github. Doesn't it make sense to build your local changes the same way as they would be built in the PR and later for release?

**Comment by ThomDietrich** [comment]
I agree with that thought.

**Pull request closed without merging**
